name: Add Sponsor Labels

on:
  workflow_call:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
      
# permissions:
#   issues: write
#   pull-requests: write
#   contents: read
permissions: write-all

jobs:
  sponsors:
    name: Label Sponsors
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/is-sponsor-label-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
